extends Control

## Scene variables
@onready var new_character = get_node("Character/NewCharacter")

## Vars
@onready var button_new = get_node("VBoxContainer/Menu/ButtonNew")
@onready var menu = get_node("VBoxContainer/Menu")

func _ready() -> void:
	pass
	
func _on_button_quit_pressed() -> void:
	get_tree().quit()
	
func _on_new_pressed() -> void:
	toggle_mode()
	
func toggle_mode() -> void:
	new_character.visible = !new_character.visible
	if menu.is_visible_in_tree():
		menu.hide()
	else:
		menu.show()
